FROM quay.io/fedora/fedora@sha256:5d0de57cb6daeb29ab5d4c898d00b21af962fb77aeabbc40bcd190d8a92f372d AS keylime_base
LABEL version="_version_" description="Keylime Base - Only used as an base image for derived packages"
MAINTAINER Keylime Team <main@keylime.groups.io>

RUN dnf -y install \
    awk \
    dnf-plugins-core \
    efivar-devel \
    efivar-libs \
    git \
    nc \
    python3-PyMySQL \
    python3-jinja2 \
    python3-psycopg2 \
    tpm2-tools
