#testing-farm:centos-stream-10-x86_64:fast
#

name: Trigger Full Test on Fast Success
on:
  check_run:
    types: [completed]

jobs:
  trigger-full:
    # We only act if the finished check was the Packit "fast" test and it was successful
    if: >
      github.event.check_run.conclusion == 'success' &&
      contains(github.event.check_run.name, ':fast')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Full Test
        run: gh pr comment ${{ github.event.pull_request.number }} --body "/packit test --identifier full"
        env:
          GITHUB_TOKEN: ${{ secrets.KEYLIME_REPO_COMMENT_TOKEN }}
